### ISSUE TITLE
Dashboard Class

### ISSUE THREAD

**Issue by sparthaje** [tjrov/p2s#8]
Create a gui class in `frontend/dashboard/__init__.py`. This class should create the needed objects for tkinter (`root`). It should also create a `Canvas` object and add it to the root. It should also have an update method that just calls `root.update()`. This way the `frontend` package can update both the `dashboard` and camera `viewfinder` simultaneously. We will also be using Matplotlib.

Name the branch `feature-8`

**Comment by Patton6** [comment]
We will also be using Matplotlib
