### ISSUE TITLE
Viewfinder Class

### ISSUE THREAD

**Issue by sparthaje** [tjrov/p2s#9]
This should be a simple `ViewFinder` class in `frontend/viewfinder/__init__.py` that finds a camera and shows an image from it. It should have an update method which updates the image shown. This way the `frontend` package can update both the `dashboard` and camera `viewfinder` simultaneously.

Name the branch `feature-9`

**Comment by derpmastear** [comment]
Finished with the "Added Viewfinded Pull Request"

**Comment by derpmastear** [comment]
im stupid

**Comment by sparthaje** [comment]
Using a raspberry pi on the ROV means the image will be transferred via sockets. Therefore, we don't need a ViewFinder class (it can be built into the dashboard)
